# Generated by Django 5.1.5 on 2025-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/default.png", upload_to="avatars/"
            ),
        ),
    ]
