# Generated by Django 5.1.5 on 2025-02-16 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_task_collaborators_task_responsible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Opcional. Adicione pessoas relevantes para acompanhar a tarefa.",
                related_name="tasks_collaborators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
